include:
  - project: syseleven/gitlab-ci-templates
    file: DockerBuild-kaniko.yml
    ref: 1.6.1

kaniko-build-master:
  tags:
    - metakube
    - shared

kaniko-build-master-dockerhub:
  extends: kaniko-build-master
  variables:
    CI_REGISTRY: 'https://index.docker.io/v1/'
    CI_REGISTRY_USER: $DOCKERHUBUSER
    CI_REGISTRY_PASSWORD: $DOCKERHUBTOKEN
    IMAGE_NAME: syseleven/kubectl-helm

kaniko-build-tags:
  tags:
    - metakube
    - shared

kaniko-build-tags-dockerhub:
  extends: kaniko-build-tags
  variables:
    CI_REGISTRY: 'https://index.docker.io/v1/'
    CI_REGISTRY_USER: $DOCKERHUBUSER
    CI_REGISTRY_PASSWORD: $DOCKERHUBTOKEN
    IMAGE_NAME: syseleven/kubectl-helm

kaniko-build:
  tags:
    - metakube
    - shared
