include:
  - project: syseleven/gitlab-ci-templates
    file: DockerBuild-kaniko.yml
    ref: 1.3.0

kaniko-build-master:
  tags:
    - metakube
    - shared

kaniko-build-master-dockerhub:
  extends: kaniko-build-master
  variables:
    CI_REGISTRY: 'https://index.docker.io/v1/'
    CI_REGISTRY_USER: $DOCKERHUBUSER
    CI_REGISTRY_PASSWORD: $DOCKERHUBTOKEN
    IMAGE_NAME: syseleven/kubectl-helm

kaniko-build-tags:
  extends: .kaniko-build-base
  variables:
    DOCKERFILE: Dockerfile
    IMAGE_TAG: "${CI_COMMIT_TAG}"
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile "${CI_PROJECT_DIR}/${DOCKERFILE}" ${DOCKER_BUILD_ARGS} --destination "${IMAGE_NAME}:${IMAGE_TAG}"
  tags:
    - metakube
    - shared
  only:
    - tags

kaniko-build-tags-dockerhub:
  extends: kaniko-build-tags
  variables:
    CI_REGISTRY: 'https://index.docker.io/v1/'
    CI_REGISTRY_USER: $DOCKERHUBUSER
    CI_REGISTRY_PASSWORD: $DOCKERHUBTOKEN
    IMAGE_NAME: syseleven/kubectl-helm

kaniko-build:
  tags:
    - metakube
    - shared
